name: Benchmark Tests

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  benchmark-tests:
    permissions:
      contents: write # required for pushing benchmark results to gh-pages
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - "22"
    runs-on: oracle-bare-metal-64cpu-512gb-x86-64
    container:
      image: ubuntu:24.04@sha256:66460d557b25769b102175144d538d88219c077c678a49af4afca6fbfc1b5252
    timeout-minutes: 10
    steps:
      # Apt packages:
      # - git: Needed for 'npm run submodule'
      - name: Setup container environment
        run: |
          apt-get update && apt-get install --fix-missing -y git

      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      # Avoid "detected dubious ownership in repository" error when running
      # `npm run submodule`.
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
          node-version: ${{ matrix.node_version }}

      - run: npm install -g npm@11.6.0

      - name: Bootstrap
        run: npm ci --ignore-scripts

      - name: Build ðŸ”§
        run: npm run compile

      - name: Benchmark tests
        run: |
          npm run test:bench
          find . -name .benchmark-results.txt -exec cat {} + > combined_benchmarks.txt

      - name: Store benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'benchmarkjs'
          output-file-path: combined_benchmarks.txt
          gh-pages-branch: gh-pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          benchmark-data-dir-path: "benchmarks"
          auto-push: true
