name: Benchmark Tests

on:
  push:
    branches: [ main ]
  # XXX just adding this to try the benchmark run on this PR. Normally we only run the benchmarks for merges to main.
  # TODO: remove this on.pull_request before merging.
  pull_request:

permissions:
  contents: read

jobs:
  benchmark-tests:
    permissions:
      contents: write # required for pushing benchmark results to gh-pages
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - "22"
    runs-on: oracle-bare-metal-64cpu-512gb-x86-64
    container:
      image: ubuntu:24.04
    timeout-minutes: 10
    env:
      NPM_CONFIG_UNSAFE_PERM: true
    steps:
      # Apt packages:
      # - git: Needed for 'npm run submodule'
      - name: Setup container environment
        run: |
          apt-get update && apt-get install --fix-missing -y build-essential curl git

      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
          node-version: ${{ matrix.node_version }}

      - run: npm install -g npm@latest

      - name: Bootstrap
        run: npm ci

      - name: Build ðŸ”§
        run: npm run compile

      - name: Benchmark tests
        run: |
          npm run test:bench
          find . -name .benchmark-results.txt -exec cat {} + > combined_benchmarks.txt

      - name: Store benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'benchmarkjs'
          output-file-path: combined_benchmarks.txt
          gh-pages-branch: gh-pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          benchmark-data-dir-path: "benchmarks"
          auto-push: true
