name: Bundler tests

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  bundler-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
          node-version: 24
      - run: npm install -g npm@latest
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Build TypeScript packages
        run: npm run compile
      - name: Run bundler tests
        run: npm run test:bundle
