name: Bundler tests

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  bundler-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
          node-version: 24
      - run: npm install -g npm@11.6.0
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Build TypeScript packages
        run: npm run compile
      - name: Run bundler tests
        run: npm run test:bundle
