name: Ensure API Peer Dependency

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  peer-api-check:
    runs-on: ubuntu-latest
    container:
      image: node:24@sha256:34af25027ee1b8bffd482ba995ec1e577fbd398db87beb4c60b80c2c9c025127
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install script dependencies
        run: npm ci --ignore-scripts

      - name: Check API dependency semantics
        run: npx nx run-many -t peer-api-check
